### ISSUE TITLE
Improve performance of file transfer tests

### ISSUE THREAD

**Issue by Stebalien** [ipfs/interop#110]
They currently take 12 minutes on CI. We should either improve the performance, or somehow split them into multiple files so we can run multiple jobs in parallel.

**Comment by achingbrain** [comment]
These are down to 5m currently 🎉 

https://app.circleci.com/pipelines/github/ipfs/go-ipfs/3033/workflows/81d4f297-5b5b-43a6-a96c-ebf574577da0/jobs/35452/parallel-runs/2/steps/2-108

**Comment by Stebalien** [comment]
:heart:
