### ISSUE TITLE
circuit interop - `browser-browser-go` failing

### ISSUE THREAD

**Issue by dryajov** [ipfs/interop#16]
When connection to a `go` node over a `browser` relay from another `browser` node, the relay fails. The two browser nodes are connected over `websocket-star`.

cc @vyzo

**Comment by dryajov** [comment]
Here is a pcap capture from the establish relay step - [browser-browser-go.pcapng.zip](https://github.com/ipfs/interop/files/1791099/browser-browser-go.pcapng.zip)

**Comment by diasdavid** [comment]
Was this fixed with https://github.com/libp2p/go-libp2p-circuit/pull/30 ?

**Comment by dryajov** [comment]
Yep, it's taken care of there, but it's not going to be released until later, so perhaps it's worth keeping this around to track when that fix is finally released?

**Comment by diasdavid** [comment]
@Stebalien refresh my memory, were the mplex + circuit relay fixes released with 0.4.15?

**Comment by Stebalien** [comment]
No, they're in the latest master.

**Comment by diasdavid** [comment]
One daaaaaaay 🎶

**Comment by Stebalien** [comment]
@dryajov this appears to work. Has this been fixed?

**Comment by Stebalien** [comment]
Nevermind...
