### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by Stebalien** [ipfs/interop#30]
Please save stderr, stdout, and any errors for failed tests to files.

**Comment by Stebalien** [comment]
Also, when a test fails, we need to actually *print* the error. Currently, I just get a test number and the name of the test in red with no explanation for what went wrong or why I'm even seeing this.

**Comment by alanshaw** [comment]
By default mocha (the test runner) will save up the output until all the tests are done and then print the failed tests along with the error messages. If you want to fail fast and print the error immediately run `npm run test -- --bail`. Hope that helps!

**Comment by Stebalien** [comment]
> If you want to fail fast and print the error immediately...

Thanks, that will definitely help.

However, it would still be nice to get the *daemon*'s stderr/stdout.

**Comment by alanshaw** [comment]
In the new https://github.com/ipfs/js-ipfsd-ctl you can use the env var `DEBUG=ipfsd-ctl:daemon:std*` to get daemon logs.
