### ISSUE TITLE
Should work when other IPFS nodes are running.

### ISSUE THREAD

**Issue by Stebalien** [ipfs/interop#31]
Currently, the pubsub tests (at least) fail when my local IPFS daemon is running. Ideally, we'd use ephemeral ports for all IPFS daemons.

**Comment by alanshaw** [comment]
This is likely because the tests have been coded to wait for a single message from a specific peer.

e.g. https://github.com/ipfs/interop/blob/1fd66fdce826a976882a11a52c24019e8bd10f97/test/pubsub.js#L181-L188
