### ISSUE TITLE
Test a single subsystem

### ISSUE THREAD

**Issue by Stebalien** [ipfs/interop#40]
As far as I can tell, there's no way to just test a single subsystem without editing files.

**Comment by magik6k** [comment]
I use `npx aegir test --grep circuit`, it seems to work well enough

**Comment by diasdavid** [comment]
Or `npm run test -- --grep="whatever"`

**Comment by Stebalien** [comment]
Ah, got it. I really wish `npm run test --help` worked but, oh well...
