### ISSUE TITLE
Convert tests to use `async/await`

### ISSUE THREAD

**Issue by achingbrain** [ipfs/interop#84]
As part of the [great migration to async iterators](https://github.com/ipfs/js-ipfs/issues/1670) we need to convert our tests to use async/await.  This is often best done separately from converting the tested code from callbacks to promises.

This repo's tests need converting.

**Comment by PedroMiguelSS** [comment]
This issue will be tackled following these steps:
- [ ] Update `ipfsd-ctl` version to support promises and make the necessary changes to make sure the tests can run successfully
- [ ] Change all the tests to use the same utils file (`daemon.js`) to init and spawn the daemons
- [ ] Update the util file to be consistent with what's being done on `js-ipfs-http-client` tests
- [x] Change the tests to use async/await

**Comment by achingbrain** [comment]
Fixed by #87
