### ISSUE TITLE
Hashes mismatch on file.js test suite

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs/interop#88]
While tackling #84 I've updated `ipfsd-ctl` to its latest version (`v0.47.1` at the moment of this writing). Immediatly, 3 tests of `file.js` started to fail. The tests are:

- **trickle DAGs**
<img width="680" alt="trickle" src="https://user-images.githubusercontent.com/11461281/66052798-1a597180-e529-11e9-9340-fb38dc033080.png">

- **rabin chunker**
<img width="680" alt="rabin" src="https://user-images.githubusercontent.com/11461281/66052805-1fb6bc00-e529-11e9-896b-cb98e5fa2040.png">

- **rabin chunker small chunks**
<img width="679" alt="rabin small" src="https://user-images.githubusercontent.com/11461281/66052828-26453380-e529-11e9-9e6b-de7b217707f9.png">

I've debugged it and I found out that this problem only occurs on versions of `ipfsd-ctl` greater than `v0.46.0`. Why? There is one [commit](https://github.com/ipfs/js-ipfsd-ctl/commit/2f61eef416bbed360e724f562da7bd119d9259d7) that updates several dependencies. One of the updated dependencies is the `ipfs-http-client` and it was updated from `v34.0.0` to `v35.1.0`. Thus, there was a breaking change and the `add` method was changed as we can see [here](https://github.com/ipfs/js-ipfs-http-client/commit/9616aed5ece058a3c98d12aa2dbe2999d08acb1f).

The tests are currently skipped but this problem must be solved asap.

**Comment by achingbrain** [comment]
This has been fixed in #86
