### ISSUE TITLE
Fix `exchange files` failing tests on Windows

### ISSUE THREAD

**Issue by dryajov** [ipfs/interop#9]
The `exchange files` (https://github.com/ipfs/interop/blob/master/test/exchange-files.js) tests are failing on windows, possibly due to `random-fs` issues (described here https://github.com/ipfs/interop/pull/7#issuecomment-360880175). This issue is here to track further work to make the tests pass on windows.

**Comment by diasdavid** [comment]
They are now passing :)

**Comment by diasdavid** [comment]
They actually never got enabled. Testing them now here #28
