### ISSUE TITLE
CI fails because no go-ipfs doesn't accept 1024 bits anymore

### ISSUE THREAD

**Issue by daviddias** [ipfs/interop#92]
See 
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/1211152/67748623-a036e280-fa2b-11e9-986e-c4b209b28b67.png">
from https://circleci.com/gh/ipfs/go-ipfs/21905?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

This https://github.com/ipfs/interop/blob/master/test/utils/daemon.js#L12 and all the others need to change to 2048 at minimum.

**Comment by Stebalien** [comment]
This has been fixed.
